export enum BlogReducerEnum {
  SET_ARTICLES = "SET_ARTICLES",
  SET_NEWS = "SET_NEWS",
  SET_PAGINATION_DATA = "SET_PAGINATION_DATA",
  SET_VIEW = "SET_VIEW",
  SET_SEARCH = "SET_SEARCH",
  SET_SELECTED_CARD = "SET_SELECTED_CARD",
}
